python3 svgeditor2.py our2/bookland/drawing.svg tem_bck/base2/bookland/drawing.svg evaluation/our2/our2_bookland/drawing_node_shape_currected.svg evaluation/our2/our2_bookland/drawing.svg bookland/G.dot evaluation/our2/our2_bookland/G.dot bookland/H.dot evaluation/our2/our2_bookland/H.dot
python3 svgeditor2.py our2/musicland/drawing.svg tem_bck/base2/musicland/drawing.svg evaluation/our2/our2_musicland/drawing_node_shape_currected.svg evaluation/our2/our2_musicland/drawing.svg musicland/G.dot evaluation/our2/our2_musicland/G.dot musicland/H.dot evaluation/our2/our2_musicland/H.dot
python3 svgeditor2.py our2/recipies/drawing.svg tem_bck/base2/recipies/drawing.svg evaluation/our2/our2_recipies/drawing_node_shape_currected.svg evaluation/our2/our2_recipies/drawing.svg recipies/G.dot evaluation/our2/our2_recipies/G.dot recipies/H.dot evaluation/our2/our2_recipies/H.dot
python3 svgeditor2.py our2/tradeland/drawing.svg tem_bck/base2/tradeland/drawing.svg evaluation/our2/our2_tradeland/drawing_node_shape_currected.svg evaluation/our2/our2_tradeland/drawing.svg tradeland/G.dot evaluation/our2/our2_tradeland/G.dot tradeland/H.dot evaluation/our2/our2_tradeland/H.dot
python3 svgeditor2.py our2/universities/drawing.svg tem_bck/base2/universities/drawing.svg evaluation/our2/our2_universities/drawing_node_shape_currected.svg evaluation/our2/our2_universities/drawing.svg universities/G.dot evaluation/our2/our2_universities/G.dot universities/H.dot evaluation/our2/our2_universities/H.dot

python3 svgeditor2.py our3/bookland/drawing.svg tem_bck/base2/bookland/drawing.svg evaluation/our3/our3_bookland/drawing_node_shape_currected.svg evaluation/our3/our3_bookland/drawing.svg bookland/G.dot evaluation/our3/our3_bookland/G.dot bookland/H.dot evaluation/our3/our3_bookland/H.dot
python3 svgeditor2.py our3/musicland/drawing.svg tem_bck/base2/musicland/drawing.svg evaluation/our3/our3_musicland/drawing_node_shape_currected.svg evaluation/our3/our3_musicland/drawing.svg musicland/G.dot evaluation/our3/our3_musicland/G.dot musicland/H.dot evaluation/our3/our3_musicland/H.dot
python3 svgeditor2.py our3/recipies/drawing.svg tem_bck/base2/recipies/drawing.svg evaluation/our3/our3_recipies/drawing_node_shape_currected.svg evaluation/our3/our3_recipies/drawing.svg recipies/G.dot evaluation/our3/our3_recipies/G.dot recipies/H.dot evaluation/our3/our3_recipies/H.dot
python3 svgeditor2.py our3/tradeland/drawing.svg tem_bck/base2/tradeland/drawing.svg evaluation/our3/our3_tradeland/drawing_node_shape_currected.svg evaluation/our3/our3_tradeland/drawing.svg tradeland/G.dot evaluation/our3/our3_tradeland/G.dot tradeland/H.dot evaluation/our3/our3_tradeland/H.dot
python3 svgeditor2.py our3/universities/drawing.svg tem_bck/base2/universities/drawing.svg evaluation/our3/our3_universities/drawing_node_shape_currected.svg evaluation/our3/our3_universities/drawing.svg universities/G.dot evaluation/our3/our3_universities/G.dot universities/H.dot evaluation/our3/our3_universities/H.dot

